spring:
  application:
    name: chat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CHAT_DATASOURCE_URL}
    username: ${CHAT_DATASOURCE_USERNAME}
    password: ${CHAT_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.service.jta.JtaPlatform
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      uri: ${CHAT_MONGODB_URI}
      database: ${CHAT_MONGODB_DATABASE}

  kafka:
    chat-room:
      group-id: chat-room-group
    chat:
      group-id: chat-group
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: chat-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  main:
    allow-bean-definition-overriding: true

server:
  port: 8087