plugins {
	id 'com.palantir.docker' version "0.35.0"
}

group = 'com.moim.comment'
version = 'latest'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}
ext {
	set('querydslVersion', "5.0.0")
	set('springCloudVersion', "2024.0.1")
}

dependencies {
	// 분산 추적
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'io.micrometer:micrometer-tracing-bridge-otel'
	implementation "com.google.protobuf:protobuf-java:3.25.3"
	implementation platform('io.micrometer:micrometer-bom:1.14.6')
	implementation 'io.micrometer:micrometer-registry-otlp'
	implementation 'io.opentelemetry:opentelemetry-exporter-otlp'
	implementation 'io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0:2.15.0-alpha'

	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	//common 모듈
	implementation project(':common')

	//mysql
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	runtimeOnly 'com.mysql:mysql-connector-j'

	//QUERY DSL
	implementation "com.querydsl:querydsl-jpa:${querydslVersion}:jakarta"
	annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jakarta"
	annotationProcessor "jakarta.annotation:jakarta.annotation-api"
	annotationProcessor "jakarta.persistence:jakarta.persistence-api"

	//validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// eureka
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

	// openfeign
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

	// env
	implementation("io.github.cdimascio:java-dotenv:5.2.2")

	// spring security
	implementation "org.springframework.boot:spring-boot-starter-security"

	//redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

tasks.register("prepareKotlinBuildScriptModel"){}

tasks.named('test') {
	useJUnitPlatform()
}

docker {
	println(tasks.bootJar.outputs.files)
	name rootProject.name+'-'+project.name + ":" + version
	dockerfile file('../Dockerfile')
	files tasks.bootJar.outputs.files
	buildArgs(['JAR_FILE': tasks.bootJar.outputs.files.singleFile.name])
}