server:
  port: 8081

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    url: ${NOTIFICATION_DB_URL}
    username: ${NOTIFICATION_DB_USERNAME}
    password: ${NOTIFICATION_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true

management:
  #  server:
  #    port: 10100
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, health, info
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    prometheus:
      access: unrestricted
