### signup
POST http://localhost:19091/api/v1/users/signup
Content-Type: application/json

{
  "username": "username",
  "password": "1q2w3e4rR!",
  "name": "홍길동"
}

### login
POST http://localhost:19091/api/v1/users/login
Content-Type: application/json

{
  "username": "username",
  "password": "1q2w3e4rR!"
}

### logout
POST http://localhost:19091/api/v1/users/logout
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzMDIzNDBiMi0wMmMzLTRiN2MtYmYzMy02YTAwMGIyMGJkY2YiLCJzdWIiOiIwYTlkZjAyNi1jMGQzLTQ1MmMtYTQ2Zi0yMzQ1ODVlMjBlYjMiLCJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaXNzIjoiaHR0cHM6Ly9tb2ltLmNvbSIsImlhdCI6MTc0NTU0Nzg2NCwiZXhwIjoxNzQ1NTQ5NjY0fQ.3Mi5lFz2HRFAtHGYSI3l05xTpy2KFE1UGLEFkhD0crM; Path=/; Max-Age=1800; Expires=Fri, 25 Apr 2025 02:54:24 GMT; Secure; HttpOnly; SameSite=LAXr
// Cookie: refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI2MmY1YjhkNy00MjRmLTQyYzQtOTI5MS00MGI1NTMxYWEyNWMiLCJzdWIiOiI2OTlkM2NjMC04MTY4LTQzYTYtYjU3Zi05ZTY1ZWNhMDQzYzUiLCJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaXNzIjoiaHR0cHM6Ly9tb2ltLmNvbSIsImlhdCI6MTc0NTU0NjM2MSwiZXhwIjoxNzQ2MTUxMTYxfQ.BjLABkYOYxzqpQTh33uDNL0zRy0wTnMp3Eup36IjP5w; Path=/api/v1/auth/refresh; Max-Age=604800; Expires=Fri, 02 May 2025 01:59:21 GMT; Secure; HttpOnly; SameSite=STRICT

### 유저 조회 by TrackingId
GET http://localhost:8082/internal/v1/users/a03730a3-9163-43ce-87db-ef40be8e6b6f

### 액세스토큰 재발급
POST http://localhost:19091/api/v1/users/refresh
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhMDM3MzBhMy05MTYzLTQzY2UtODdkYi1lZjQwYmU4ZTZiNmYiLCJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaXNzIjoiaHR0cHM6Ly9tb2ltLmNvbSIsImlhdCI6MTc0NTI1NTY5MywiZXhwIjoxNzQ1ODYwNDkzfQ.k3CcLHwsamEiR3H8h-1WSw6t8mNJMsAEiS9DyY-hCpA; Path=/api/v1/auth/refresh; Max-Age=604800; Expires=Mon, 28 Apr 2025 17:14:53 GMT; Secure; HttpOnly; SameSite=STRICT

### 회원 업데이트
PUT http://localhost:19091/api/v1/users/a03730a3-9163-43ce-87db-ef40be8e6b6f
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlNTI3YTBjZS1jDlhLTRiMWUtYTcxYy03ODI2NjdhYWM3MWMiLCJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaXNzIjoiaHR0cHM6Ly9tb2ltLmNvbSIsImlhdCI6MTc0NTI1NjYxNSwiZXhwIjoxNzQ1MjU4NDE1fQ.uO-EGFSGom26cAJT8PfZngK69q65rOu2L9cPo6YkA1Q; Path=/; Max-Age=1800; Expires=Mon, 21 Apr 2025 18:00:16 GMT; Secure; HttpOnly; SameSite=LAX

{
  "name": "이순신"
}

### 회원 탈퇴(삭제)
DELETE http://localhost:8082/api/v1/users/1ee56098-5cb4-4a95-bb8d-71035f11665e

### 회원 검색
GET http://localhost:8082/api/v1/users?
    page={{$random.integer(100)}}&
    size={{$random.integer(100)}}

### 회원 검색
GET http://localhost:19091/api/v1/users?page=1&size=10
