### signup
POST http://localhost:19091/api/v1/users/signup
Content-Type: application/json

{
  "username": "username",
  "password": "1q2w3e4rR!",
  "name": "홍길동"
}

### login
POST http://localhost:19091/api/v1/users/login
Content-Type: application/json

{
  "username": "username",
  "password": "1q2w3e4rR!"
}

### logout
POST http://localhost:19091/api/v1/users/logout
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1YThmMzAwNC1mZWNmLTQ0ZGMtYTAzYi1jMjlkOGNiMjUzNzciLCJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaXNzIjoiaHR0cHM6Ly9tb2ltLmNvbSIsImlhdCI6MTc0NTI1NTI4MCwiZXhwIjoxNzQ1MjU3MDgwfQ.k7nbNHIs2AikRzFdtUTkfMpd0-t-gbKuqYvsdWJjhh8; Path=/; Max-Age=1800; Expires=Mon, 21 Apr 2025 17:38:00 GMT; Secure; HttpOnly; SameSite=LAX

### 유저 조회 by TrackingId
GET http://localhost:8082/internal/v1/users/69207ff8-c757-477a-89a3-b79bab50f696

### 액세스토큰 재발급
POST http://localhost:19091/api/v1/users/refresh
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1YThmMzAwNC1mZWNmLTQ0ZGMtYTAzYi1jMjlkOGNiMjUzNzciLCJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaXNzIjoiaHR0cHM6Ly9tb2ltLmNvbSIsImlhdCI6MTc0NTI1NTI1MiwiZXhwIjoxNzQ1ODYwMDUyfQ.McaZmOOcksLE62pil80x4HNA1fr9AdAaMa2uPjA0Glc; Path=/api/v1/auth/refresh; Max-Age=604800; Expires=Mon, 28 Apr 2025 17:07:32 GMT; Secure; HttpOnly; SameSite=STRICT

### 회원 업데이트
PUT http://localhost:8082/api/v1/users/1ee56098-5cb4-4a95-bb8d-71035f11665e
Content-Type: application/json

{
  "name": "이순신"
}

### 회원 탈퇴(삭제)
DELETE http://localhost:8082/api/v1/users/1ee56098-5cb4-4a95-bb8d-71035f11665e

### 회원 검색
GET http://localhost:8082/api/v1/users?
    page={{$random.integer(100)}}&
    size={{$random.integer(100)}}

### 회원 검색
GET http://localhost:19091/api/v1/users?page=1&size=10
