plugins {
	id 'com.epages.restdocs-api-spec' version "0.19.4"
	id 'com.palantir.docker' version "0.35.0"
}

group = 'com.sparta.session'
version = 'latest'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

ext {
	set('querydslVersion', "5.0.0")
	set('springCloudVersion', "2024.0.0")
}


dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

dependencies {
	// 분산 추적
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'io.micrometer:micrometer-tracing-bridge-otel'
	implementation "com.google.protobuf:protobuf-java:3.25.3"
	implementation platform('io.micrometer:micrometer-bom:1.14.6')
	implementation 'io.micrometer:micrometer-registry-otlp'
	implementation 'io.opentelemetry:opentelemetry-exporter-otlp'
	implementation 'io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0:2.15.0-alpha'

	implementation project (":common")
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

	//QUERY DSL
	implementation "com.querydsl:querydsl-jpa:${querydslVersion}:jakarta"
	annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jakarta"
	annotationProcessor "jakarta.annotation:jakarta.annotation-api"
	annotationProcessor "jakarta.persistence:jakarta.persistence-api"

	// openfeign
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	runtimeOnly 'org.postgresql:postgresql'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	runtimeOnly 'com.mysql:mysql-connector-j'
	implementation "org.springframework.boot:spring-boot-starter-security"

	//DOCS
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'
	testImplementation 'com.epages:restdocs-api-spec-mockmvc:0.19.2'

	// redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.redisson:redisson-spring-boot-starter:3.28.0'
	runtimeOnly 'com.h2database:h2'
}

def querydslSrcDir = 'src/main/generated'
clean {
	delete file(querydslSrcDir)
}

// 컴파일 시 빌드 폴더를 지웁니다.
compileJava {
	dependsOn 'clean'
}

// OpenApi에 들어갈 메타데이터를 추가합니다.
// 모놀리식일 경우 해당 프로젝트의 주소를 입력하고,
// MSA일 경우 게이트웨이의 주소를 입력하면 됩니다.
openapi3 {
	server = 'http://localhost:8089'
	title = 'SESSION API'
	description = '세션에 관련된 api 문서 입니다'
	version = '1.0.0'
	format = 'json'
	tagDescriptionsPropertiesFile = 'src/docs/tag-descriptions.yaml'

	separatePublicApi = true
}

tasks.register('setDocs') {
	dependsOn 'openapi3'
	doLast {
		copy {
			from "build/api-spec"
			include "*.json"
			include "*.yaml"
			into "build/resources/main/static/springdoc"
			rename { String fileName ->
				if (fileName.endsWith('.json')) {
					return fileName.replace('.json', '-session-service.json')
				} else if (fileName.endsWith('.yaml')) {
					return fileName.replace('.yaml', '-session-service.yml')
				}
				return fileName
			}
		}
	}
}

// bootRun 실행 시 문서 생성 태스크를 실행합니다.
bootRun {
	dependsOn 'setDocs'
}

// bootJar 실행 시 문서 생성 태스크를 실행합니다.
bootJar {
	dependsOn 'setDocs'
}

tasks.named('test') {
	useJUnitPlatform()
}

docker {
	println(tasks.bootJar.outputs.files)
	name rootProject.name+'-'+project.name + ":" + version
	dockerfile file('../Dockerfile')
	files tasks.bootJar.outputs.files, rootProject.file('entrypoint.sh')
	buildArgs(['JAR_FILE': tasks.bootJar.outputs.files.singleFile.name])
}
