spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${POST_DATASOURCE_URL}
    username: ${POST_DATASOURCE_USERNAME}
    password: ${POST_DATASOURCE_PASSWORD}
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    mongodb:
      uri: mongodb://post:moimserver@localhost:27017/post?authSource=admin
      database: post

  # Redis 필요시
#  data:
#    redis:
#      host: localhost
#      port: 6379