server:
  port: 8088

spring:
  application:
    name: post-service
  config:
    import:
      - "application-database.yml"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true