eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
#      defaultZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost    # 추가: 호스트명 명시적 설정
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}  # 추가: 인스턴스 ID 설정

spring:
  kafka:
    feed:
      group-id: ${FEED_GROUP_ID}
    vote:
      group-id: ${VOTE_GROUP_ID}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: post-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

feign:
  url:
    organization: ${ORGANIZATION_CLIENT_URL}