server:
  port: 8088

spring:
  application:
    name: post-service
  config:
    import:
      - "application-database.yml"
      - "application-external.yml"
  security:
    user:
      name: user
      password: 1234

