spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${POST_DATASOURCE_URL}
    username: ${POST_DATASOURCE_USERNAME}
    password: ${POST_DATASOURCE_PASSWORD}
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false

  data:
    mongodb:
      uri: ${POST_MONGODB_URI}
      database: ${POST_MONGODB_DATABASE}



  # Redis 필요시
#  data:
#    redis:
#      host: localhost
#      port: 6379