package com.sparta.moim.user.domain.repository;

import com.sparta.moim.common.config.JpaConfig;
import com.sparta.moim.user.domain.model.User;
import com.sparta.moim.user.domain.UserRepository;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Import(JpaConfig.class)
class UserRepositoryTest {

  @Autowired
  UserRepository userRepository;

  @Nested
  @DisplayName("user save")
  class save {

    @Test
    @DisplayName("trackingId가 자동 생성된다.")
    void trackingIdAutoGenerated() {
      User user = User.createUser(
          "testUsername",
          "testPassword",
          "testName"
      );

      User savedUser = userRepository.save(user);
      Assertions.assertThat(savedUser.getTrackingId()).isNotNull();
      Assertions.assertThat(savedUser.getTrackingId().toString().length()).isEqualTo(36);
    }
  }
}