eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
    ip-address: ${ECS_INSTANCE_IP_ADDRESS}
    instance-id: ${spring.application.name}:${ECS_INSTANCE_IP_ADDRESS}:${server.port}

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_COLLECTOR_TRACES_ENDPOINT}
    logging:
      endpoint: ${OTEL_COLLECTOR_LOGS_ENDPOINT}
    metrics:
      export:
        url: ${OTEL_COLLECTOR_METRICS_ENDPOINT}

  # actuator endpoint를 외부에서 볼 수 있도록
  endpoints:
    web:
      exposure:
        include: "*"


#spring:
#  kafka:
#    chat-room:
#      group-id: chat-room-group
#    chat:
#      group-id: chat-group
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
#    consumer:
#      group-id: chat-group
#      auto-offset-reset: latest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer