spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SCHEDULE_DATASOURCE_URL}
    username: ${SCHEDULE_DATASOURCE_USERNAME}
    password: ${SCHEDULE_DATASOURCE_PASSWORD}
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  # Redis 필요시
#  data:
#    redis:
#      host: localhost
#      port: 6379