server:
  port: 8082

spring:
  application:
    name: user-service
  data:
    redis:
      host: ${USER_REDIS_HOST}
      port: ${USER_REDIS_PORT}
      password: ${USER_REDIS_PASSWORD}

  datasource:
    url: ${USER_DATABASE_URL}
    username: ${USER_DATABASE_ID}
    password: ${USER_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DISCOVERY_URL}
    register-with-eureka: true
    fetch-registry: true

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_COLLECTOR_TRACES_ENDPOINT}
    logging:
      endpoint: ${OTEL_COLLECTOR_LOGS_ENDPOINT}
    metrics:
      export:
        url: ${OTEL_COLLECTOR_METRICS_ENDPOINT}

  # actuator endpoint를 외부에서 볼 수 있도록
  endpoints:
    web:
      exposure:
        include: "*"