spring:
  application:
    name: user-service
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3308/user_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DISCOVERY_URL}
    register-with-eureka: true
    fetch-registry: true

jwt:
  issuer: "https://moim.com"
  secret: ${JWT_SECRET}
server:
  port: 8082