spring:
  application:
    name: session-service

  datasource:
    url: ${SESSION_DATABASE_URL:jdbc:mysql://localhost:3315/session_db}
    username: ${SESSION_DATABASE_ID:root}
    password: ${SESSION_DATABASE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true


server:
  port: 8089

feign:
  client:
    member:
      url: ${SESSION_URL:http://localhost:8089}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:19090/eureka/}

springdoc:
  swagger-ui:
    enabled: true
    path: /docs
    url: /springdoc/openapi3-session-service.json
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    enabled: true
    path: /api-docs-session-service


