spring:
  security:
    user:
      name: user
      password: 1234
  application:
    name: session-service

  datasource:
    url: jdbc:mysql://localhost:3315/session_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true


server:
  port: 8089

feign:
  client:
    member:
      url: "http://localhost:8089"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090

springdoc:
  swagger-ui:
    enabled: true
    path: /docs
    url: /springdoc/openapi3-session-service.json
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    enabled: true
    path: /api-docs-session-service


