spring:
  application:
    name: session-service

  datasource:
    url: ${SESSION_DATABASE_URL:jdbc:mysql://localhost:3315/session_db}
    username: ${SESSION_DATABASE_ID:root}
    password: ${SESSION_DATABASE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      stream-join-key: stream:session_join
      stream-leave-key: stream:session_leave
      group-join-name: session_join_group
      group-leave-name: session_leave_group
      consumer-id: session_consumer_
      poll-timeout: 1
      host: ${SESSION_REDIS_HOST:localhost}
      port: ${SESSION_REDIS_PORT:6379}
#      username: ${SESSION_REDIS_USERNAME}
#      password: ${SESSION_REDIS_PASSWORD}
      timeout: 6000
      database: 0
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:19090/eureka/}
#  instance:
#    prefer-ip-address: true
#    ip-address: ${ECS_INSTANCE_IP_ADDRESS}
#    instance-id: ${spring.application.name}:${ECS_INSTANCE_IP_ADDRESS}:8089

springdoc:
  swagger-ui:
    enabled: true
    path: /docs
    url: /springdoc/openapi3-session-service.json
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    enabled: true
    path: /api-docs-session-service

management:
  tracing:
    sampling:
      probability: 1.0
#  otlp:
#    tracing:
#      endpoint: ${OTEL_COLLECTOR_TRACES_ENDPOINT}
#    logging:
#      endpoint: ${OTEL_COLLECTOR_LOGS_ENDPOINT}
#    metrics:
#      export:
#        url: ${OTEL_COLLECTOR_METRICS_ENDPOINT}

  # actuator endpoint를 외부에서 볼 수 있도록
  endpoints:
    web:
      exposure:
        include: "*"


