spring:
  security:
    user:
      name: user
      password: 1234
  application:
    name: gathering-service

  datasource:
    url: jdbc:mysql://localhost:3311/gathering_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
      database: 0
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


member:
  service:
    url: http://localhost:8085

server:
  port: 8085

springdoc:
  swagger-ui:
    enabled: true
    path: /docs
    url: /springdoc/openapi3-gathering-service.json
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    enabled: true
    path: /api-docs-gathering-service

