server:
  port: 8084
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: organization-service

  datasource:
    url: ${ORGANIZATION_DB_URL}
    username: ${ORGANIZATION_DB_USERNAME}
    password: ${ORGANIZATION_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: organization-service
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        max.poll.interval.ms: 300000
        max.poll.records: 1000
        session.timeout.ms: 10000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_COLLECTOR_TRACES_ENDPOINT}
    logging:
      endpoint: ${OTEL_COLLECTOR_LOGS_ENDPOINT}
    metrics:
      export:
        url: ${OTEL_COLLECTOR_METRICS_ENDPOINT}

  # actuator endpoint를 외부에서 볼 수 있도록
  endpoints:
    web:
      exposure:
        include: "*"