server:
  port: 8084
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: organization-service

  datasource:
    url: jdbc:mysql://localhost:3310/organization_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 15
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
#  server:
#    port: 10100
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    prometheus:
      access: unrestricted