server:
  port: 8084

spring:
  application:
    name: organization-service

  datasource:
    url: jdbc:mysql://localhost:3310/organization_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

