spring:
  application:
    name: chat-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CHAT_DATASOURCE_URL}
    username: ${CHAT_DATASOURCE_USERNAME}
    password: ${CHAT_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.service.jta.JtaPlatform
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      uri: ${CHAT_MONGODB_URI}
      database: ${CHAT_MONGODB_DATABASE}

  kafka:
    chat:
      group-id: ${CHAT-GROUP-ID}
    consumer:
      group-id: ${CHAT-GROUP-ID}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DISCOVERY}

server:
  port: 8087

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_COLLECTOR_TRACES_ENDPOINT}
    logging:
      endpoint: ${OTEL_COLLECTOR_LOGS_ENDPOINT}
    metrics:
      export:
        url: ${OTEL_COLLECTOR_METRICS_ENDPOINT}

  # actuator endpoint를 외부에서 볼 수 있도록
  endpoints:
    web:
      exposure:
        include: "*"